name: "publish"
permissions: read-all
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      # Harden workflow runner
      - name: Harden workflow runner (audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # Prepare builder
      - name: Set up buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      # Login against a Docker registry
      - name: Log in to the Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # setup properly in the repository or organization settings
          password: ${{ secrets.ACCESS_TOKEN }}
      - name: Build and publish images
        run: |
          set -e
          npm install -g @devcontainers/cli
          chmod +x build.sh
          ./build.sh
